In [1]:
import numpy as np

Basics

In [2]:
a = np.array([1,2,3]) #1darray

In [16]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])#2darray

In [13]:
a.ndim # dimension
b.ndim

2

In [15]:
a.shape
b.shape # shape (rows,columns)

(2, 3)

Accessing/changing elements,rows,columns etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#access an element (row,column)
a[1,5]
a[0,-2]

6

In [25]:
#specific row 
a[0, :]  # : is the basic slice syntax, tells us all elements

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#specific column
a[:,4]

array([ 5, 12])

In [28]:
#[startindex:endindex;stepsize]
a[0, 1:6:2] # zeroth row, 1-6th element, stepsize 2

array([2, 3, 4, 5, 6])

# Initialising different types of Arrays

In [34]:
# Zero matrix
np.zeros((100,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
#1s matrix
np.ones((4,3,2), dtype = 'int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [38]:
# matrix of any number
np.full((3,3), 89) #(shape,number)

array([[89, 89, 89],
       [89, 89, 89],
       [89, 89, 89]])

In [53]:
m = np.ones([5,5], dtype = 'int32')
m[1,1:4]=0
m[3,1:4]=0
m[2,1]=0
m[2,3]=0
m[2,2]=9
m

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Stats

In [62]:
s = np.array([[1,2,3],[4,5,6]])
s
np.min(s, axis = 1)
np.max(s)
np.sum(s, axis=0)

array([5, 7, 9])